REAL_REPO  # unused variable (tests/_environ.py:12)
fixture_files  # unused function (tests/conftest.py:27)
fixture_git  # unused function (tests/conftest.py:18)
fixture_make_tree  # unused function (tests/conftest.py:65)
fixture_mock_environment  # unused function (tests/conftest.py:39)
s  # unused variable (lsfiles/_objects.py:40)
s  # unused variable (lsfiles/_objects.py:51)
